# pandas

In [2]:
import pandas as pd

In [5]:
import numpy as np

arr = np.arange(100, 110)
print(arr)

[100 101 102 103 104 105 106 107 108 109]


In [4]:
s = pd.Series(arr)
print(s)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64


In [6]:
s = pd.Series(arr, dtype='int32')
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int32


In [7]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series(person)
print(s)

0     kim
1     lee
2    park
3    hong
dtype: object


In [8]:
s = pd.Series([1, 2, 3, 4, '99'])
print(s)

0     1
1     2
2     3
3     4
4    99
dtype: object


## 1. indexing

In [9]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series(person)

In [10]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [12]:
s[2]

'park'

In [15]:
# s[-1] => 음수 index는 불가, error

In [18]:
# index 지정
s = pd.Series(person, index=['a', 'b', 'c', 'd']) #index=list('abcd')
print(s)

a     kim
b     lee
c    park
d    hong
dtype: object


In [19]:
# index 접근
s['a']

'kim'

In [20]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [21]:
s.values

array(['kim', 'lee', 'park', 'hong'], dtype=object)

In [22]:
s.ndim

1

In [23]:
s.shape

(4,)

## 2. NaN(Not A Number)

In [24]:
s = pd.Series(person + [np.nan])
print(s)

0     kim
1     lee
2    park
3    hong
4     NaN
dtype: object


In [26]:
arr = np.arange(50, 55)
s = pd.Series(arr, dtype='float32')
print(s)

0    50.0
1    51.0
2    52.0
3    53.0
4    54.0
dtype: float32


In [29]:
f = ['바나나', np.nan, '사과', '포도', '복숭아']
s = pd.Series(f, index=list('가나다라마'))
print(s)

가    바나나
나    NaN
다     사과
라     포도
마    복숭아
dtype: object


### 2-1. fancy indexing

In [30]:
s[['가', '나']]

가    바나나
나    NaN
dtype: object

In [32]:
s.iloc[[2, 3]]
s[['다', '라']]

다    사과
라    포도
dtype: object

### 2-2. bool

In [34]:
a = [True, False, True, False, True]
s[a]

가    바나나
다     사과
마    복숭아
dtype: object

In [35]:
arr = np.arange(5, 20)
s = pd.Series(arr)
print(s)

0      5
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
dtype: int64


In [36]:
s < 10

0      True
1      True
2      True
3      True
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [37]:
s[s < 10]

0    5
1    6
2    7
3    8
4    9
dtype: int64

In [40]:
s[s == 5]

0    5
dtype: int64

## 3. 결측치(NaN) 처리

In [41]:
s = pd.Series([2, 5, 2, 1, np.nan, 2, 4, 9, np.nan])
print(s)

0    2.0
1    5.0
2    2.0
3    1.0
4    NaN
5    2.0
6    4.0
7    9.0
8    NaN
dtype: float64


In [42]:
s.isnull()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8     True
dtype: bool

In [43]:
s[s.isnull()]

4   NaN
8   NaN
dtype: float64

In [44]:
s.isna()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8     True
dtype: bool

In [45]:
s[s.isna()]

4   NaN
8   NaN
dtype: float64

In [46]:
s[s.notnull()]

0    2.0
1    5.0
2    2.0
3    1.0
5    2.0
6    4.0
7    9.0
dtype: float64

In [51]:
s[1:3]

1    5.0
2    2.0
dtype: float64

# DataFrame

In [52]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [55]:
df = pd.DataFrame(arr)
df

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [58]:
df = pd.DataFrame(arr, 
                  columns=['가', '나', '다'], 
                  index=['a', 'b', 'c']
                 )
df

가  나  다
a  0  1  2
b  3  4  5
c  6  7  8

In [107]:
data = {
    'name': ['kim', 'lee', 'park'],
    'age': [10, 15, 20],
    'location': ['seoul', 'LA', 'tokyo']
}
df = pd.DataFrame(data)
df

name  age location
0   kim   10    seoul
1   lee   15       LA
2  park   20    tokyo

In [108]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [109]:
df.columns

Index(['name', 'age', 'location'], dtype='object')

In [110]:
df.values

array([['kim', 10, 'seoul'],
       ['lee', 15, 'LA'],
       ['park', 20, 'tokyo']], dtype=object)

In [111]:
df.dtypes

name        object
age          int64
location    object
dtype: object

In [112]:
df.T

0    1      2
name        kim  lee   park
age          10   15     20
location  seoul   LA  tokyo

In [113]:
df.index = list('abc')
df

name  age location
a   kim   10    seoul
b   lee   15       LA
c  park   20    tokyo

### column

In [114]:
df['name']

a     kim
b     lee
c    park
Name: name, dtype: object

In [115]:
type(df['name'])

pandas.core.series.Series

In [116]:
df[['name', 'location']]

name location
a   kim    seoul
b   lee       LA
c  park    tokyo

In [117]:
type(df[['name', 'location']])

pandas.core.frame.DataFrame

In [118]:
df.rename(columns={'location': 'hometown'}, inplace=True)
df

name  age hometown
a   kim   10    seoul
b   lee   15       LA
c  park   20    tokyo